name: Build libiec61850
on: [push]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Configure
        run: cmake -DBUILD_SHARED_LIBS=ON -B build .
      - name: Build
        run: cmake --build build --config Release
      - name: Upload DLL
        uses: actions/upload-artifact@v7.0.1
        with:
          name: libiec61850-windows
          path: build/**

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Configure
        run: cmake -DBUILD_SHARED_LIBS=ON -B build .
      - name: Build
        run: cmake --build build
      - name: Upload SO
        uses: actions/upload-artifact@v7.0.1
        with:
          name: libiec61850-linux
          path: build/**
